open_shade:
  name: Open Shade
  description: Opens the shade to 100% open
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

close_shade:
  name: Close Shade
  description: Closes the shade to 100% closed
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

stop_shade:
  name: Stop Shade
  description: Stops the shade at the current position
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

set_shade_postion:
  name: Set Position
  description: Sets the position to % of open
  fields:
    position:
      name: position
      description: Percentage of open for the shade
      required: true
      example: 50
      selector:
        text:
  target:
    entity:
      integration: espsomfy_rts
      domain: cover

tilt_open:
  name: Tilt Open
  description: Tilts the slats open
  target:
    integration: espsomfy_rts
    domain: cover

tilt_close:
  name: Tilt Close
  description: Tilts the slats closed
  target:
    integration: espsomfy_rts
    domain: cover

set_tilt_postion:
  name: Set Position
  description: Sets the tilt position to % of open
  fields:
    position:
      name: position
      description: Percentage of open for the shade slats
      required: true
      example: 50
      selector:
        text:
  target:
    entity:
      integration: espsomfy_rts
      domain: cover





